// src/pages/dashboardEmployer/index.vue
<script lang="ts" setup>
import {
  getStaffs,
  getStaff,
  registerStaff,
  getDepartments,
  updateStaffPassword,
  deleteStaff,
} from "@/composables/services/data/data";
import { userToast } from "@/composables/helpers/notifications";
import type { StaffData } from "@/types/data";
import XDropdown from "@/components/XDropdown.vue";
import XModal from '@/components/XModal.vue';
import XSummary from "@/components/XSummary.vue";

const isModalOpen = useState("showModal");
const $route = useRoute();
const $router = useRouter();

const state = reactive({
  firstName: "",
  lastName: "",
  email: "",
  role: "",
  department: "",
});

const columns = [

  {
    key: "firstName",
    label: "First Name",
  },
  {
    key: "lastName",
    label: "Last Name",
  },
  {
    key: "role",
    label: "Staff Role",
  },
  {
    key: "email",
    label: "Email",
  },
  {
    key: "lastEntryTime",
    label: "Last login time"
  },
  {
    key: "actions",
  },
];

const items = (row: any) => [
  [
    {
      label: "View Employee",
      icon: "i-heroicons-eye-20-solid",
      click: () => $router.push(`/dashboardStaff/${row._id}`),
    },
  ],
  [
    {
      label: "Delete Employee",
      icon: "i-heroicons-trash-20-solid",
      click: () => handleDeleteStaff(row),
    },
  ],
  [
    {
      label: "Add Password",
      icon: "i-heroicons-wrench-screwdriver-solid",
      click: () => handleAddPassword(row),
    },
  ],
];

const departmentItems = ref([]);

const loading = ref(false);
const staffData = ref<StaffData[]>([]);
const createStaff = async () => {
  loading.value = true;
  try {
    const response = await registerStaff(state);

    loading.value = false;
    userToast(["Employee Successfully Created!"], 200);
    isModalOpen.value = false;
    state.email = "";
    state.firstName = "";
    state.lastName = "";
    state.role = "";
    getData();
  } catch (error: any) {
    loading.value = false;
    const err = [error.response.data.message];
    isModalOpen.value = false;
    userToast(err, error.response.data.code);
  }
};

const pageData = reactive({
  page: 1,
  count: "5",
  total: 0,
  next: "",
  prev: "",
});

const getData = async (pageNum?: number) => {
  const data = await getStaffs(pageNum);
  data.staff.map((x:any) => {
    x.lastEntryTime = new Date(x.lastEntryTime).toLocaleString('en-US', { 
          year: 'numeric', 
          month: 'long', 
          day: 'numeric', 
          hour: 'numeric', 
          minute: 'numeric', 
          hour12: true 
      });
      })

  pageData.page = 1;
  pageData.prev = data.previous;
  pageData.next = data.next;
  pageData.total = data.count;
  staffData.value = data.staff;
};

const getPage = (page: any) => {
  if (!page) {
    getData();
  } else {
    const pageNumber = new URL(page).searchParams.get("page");
    getData(Number(pageNumber));
  }
};

const showAddEmployeeModal = ref(false);
const showAddPasswordModal = ref(false);

const handleAddEmployees = () => {
  showAddEmployeeModal.value = true;
};

// Simplified password state
interface PasswordState {
  password: string;
  confirmPassword: string;
}

const passwordState = reactive<PasswordState>({
  password: '',
  confirmPassword: ''
});

const selectedUser = ref({
  email: '',
  _id: ''
});

const handleAddPassword = (user: any) => {
  selectedUser.value = user;
  showAddPasswordModal.value = true;
};

const handlePasswordSubmit = async () => {
  if (passwordState.password !== passwordState.confirmPassword) {
    userToast(['Passwords do not match'], 400);
    return;
  }

  loading.value = true;
  try {
    await updateStaffPassword(selectedUser.value._id, passwordState.password);
    
    showAddPasswordModal.value = false;
    userToast(['Password successfully updated'], 200);
    handleModalClose('add-password');
  } catch (error: any) {
    userToast(
      [error.response?.data?.message || 'Error updating password'], 
      error.response?.status || 400
    );
  } finally {
    loading.value = false;
  }
};

const handleModalClose = (modalId: string) => {
  if (modalId === 'add-employee') {
    state.email = "";
    state.firstName = "";
    state.lastName = "";
    state.role = "";
    state.department = "";
  } else if (modalId === 'add-password') {
    selectedUser.value = { email: '', _id: '' };
    passwordState.password = '';
    passwordState.confirmPassword = '';
  }
};

const showDeleteModal = ref(false);
const selectedUserForDelete = ref({
  _id: '',
  firstName: '',
  lastName: ''
});

const handleDeleteStaff = (user: any) => {
  selectedUserForDelete.value = user;
  showDeleteModal.value = true;
};

const confirmDelete = async () => {
  loading.value = true;
  try {
    await deleteStaff(selectedUserForDelete.value._id);
    userToast(['Employee successfully deleted'], 200);
    getData(); // Refresh the table
  } catch (error: any) {
    userToast(
      [error.response?.data?.message || 'Error deleting employee'],
      error.response?.status || 400
    );
  } finally {
    loading.value = false;
    showDeleteModal.value = false;
    selectedUserForDelete.value = { _id: '', firstName: '', lastName: '' };
  }
};

onMounted( async () => {
  const depts = await getDepartments()
  departmentItems.value = depts.data.map((item: { name: any; _id: any; }) => ({
    name: item.name, // Adjust according to your data structure
    id: item._id    // Adjust according to your data structure
  }));
  getData();
});
</script>

<template>
  <main class="min-h-full bg-white dark:bg-primary-800 p-4 md:p-10">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between">
      <div class="flex flex-col mb-4 md:mb-0">
        <span class="text-xl md:text-2xl font-bold">Welcome Admin</span> 
        <span class="text-sm font-light">See Today's attendance overview..</span>
      </div>
      <div class="flex space-x-2">
        <div class="border-[#762CC0] cursor-pointer border py-3 px-5 space-x-2 rounded-md flex justify-center">
          <svg width="20" height="20" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9.922 3.29004C14.6963 1.66245 17.0834 0.848663 18.3674 2.13261C19.6513 3.41656 18.8375 5.80371 17.21 10.578L16.1016 13.8292C14.8517 17.4958 14.2267 19.3291 13.1964 19.4808C12.9195 19.5216 12.6328 19.4971 12.3587 19.4091C11.3395 19.0819 10.8007 17.1489 9.7231 13.283C9.4841 12.4255 9.3646 11.9967 9.0924 11.6692C9.0134 11.5742 8.9258 11.4866 8.8308 11.4076C8.5033 11.1354 8.0745 11.0159 7.21705 10.7769C3.35111 9.6993 1.41814 9.1605 1.0909 8.14127C1.00292 7.86724 0.97837 7.58053 1.01916 7.30355C1.17088 6.27332 3.00419 5.64834 6.6708 4.39838L9.922 3.29004Z" stroke="#1A1A1A" stroke-width="2"/>
</svg>
<span>Send Invite</span>
        </div>
        <div class="bg-[#762CC0] cursor-pointer text-white border py-3 px-5 space-x-2 rounded-md flex justify-center">
          <svg width="20" height="20" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M13 22.5H6.59087C5.04549 22.5 3.81631 21.748 2.71266 20.6966C0.453366 18.5441 4.1628 16.824 5.57757 15.9816C7.97679 14.553 10.8425 14.1575 13.5 14.7952" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M16.5 7C16.5 9.48528 14.4853 11.5 12 11.5C9.51472 11.5 7.5 9.48528 7.5 7C7.5 4.51472 9.51472 2.5 12 2.5C14.4853 2.5 16.5 4.51472 16.5 7Z" stroke="white" stroke-width="2"/>
<path d="M19 23.7426V19.5M19 19.5V15.2574M19 19.5H14.7574M19 19.5H23.2427" stroke="white" stroke-width="2" stroke-linecap="round"/>
</svg>
<span>Add employee</span>
        </div>
      </div>

     
    </div>
    <div class="mt-8 md:mt-20">
      <XSummary />
      <XTable
        :columns="columns"
        :items-generator="items"
        :table-data="staffData"
        :pagination-data="pageData"
        @prevPage="getPage"
        @nextPage="getPage"
      >
      </XTable>
    </div>
  </main>

  <!-- Add Employee Modal -->
  <XModal
    modal-id="add-employee"
    v-model="showAddEmployeeModal"
    title="Create Employee"
    size="2xl"
    @close="handleModalClose"
  >
    <UForm
      :state="state"
      class="space-y-4 justify-center flex items-center flex-col"
      :validate-on="['submit']"
    >
      <div class="space-y-5 w-full">
        <UFormField label="First Name" name="firstName" class="space-y-2">
          <UInput v-model="state.firstName" placeholder="First Name" size="lg" />
        </UFormField>

        <UFormField label="Last Name" name="lastName" class="space-y-2">
          <UInput v-model="state.lastName" placeholder="Last Name" size="lg" />
        </UFormField>

        <UFormField label="Email" name="email" class="space-y-2">
          <UInput v-model="state.email" placeholder="Email Address" size="lg" />
        </UFormField>

        <UFormField label="Role" name="role" class="space-y-2">
          <UInput v-model="state.role" placeholder="Role" size="lg" />
        </UFormField>

        <div class="flex flex-col space-y-2">
          <label for="department">Department</label>
          <XDropdown 
            :items="departmentItems" 
            @select="((val: any) => state.department = val.id)" 
          />
        </div>
      </div>
    </UForm>

    <template #footer>
      <div class="flex justify-end gap-3">
        <UButton
          color="gray"
          variant="soft"
          @click="showAddEmployeeModal = false"
        >
          Cancel
        </UButton>
        <UButton
          type="submit"
          :loading="loading"
          @click="createStaff"
        >
          Create Employee
        </UButton>
      </div>
    </template>
  </XModal>

  <!-- Add Password Modal -->
  <XModal
    modal-id="add-password"
    v-model="showAddPasswordModal"
    title="Set Password"
    size="md"
    @close="handleModalClose"
  >
    <UForm
      :state="passwordState"
      class="space-y-6"
    >
      <div class="space-y-4">
        <!-- User Info Section -->
        <div class="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg">
          <div class="text-sm text-gray-600 dark:text-gray-300">Setting password for:</div>
          <div class="font-medium text-gray-900 dark:text-white">{{ selectedUser.email }}</div>
        </div>

        <!-- Password Fields -->
        <UFormField
          label="New Password"
          name="password"
          class="space-y-2"
        >
          <UInput
            v-model="passwordState.password"
            type="password"
            placeholder="Enter new password"
            size="lg"
            autocomplete="new-password"
          />
        </UFormField>

        <UFormField
          label="Confirm Password"
          name="confirmPassword"
          class="space-y-2"
        >
          <UInput
            v-model="passwordState.confirmPassword"
            type="password"
            placeholder="Confirm new password"
            size="lg"
            autocomplete="new-password"
          />
        </UFormField>
      </div>
    </UForm>

    <template #footer>
      <div class="flex justify-end gap-3">
        <UButton
          color="gray"
          variant="soft"
          @click="showAddPasswordModal = false"
        >
          Cancel
        </UButton>
        <UButton
          :loading="loading"
          color="primary"
          @click="handlePasswordSubmit"
        >
          Set Password
        </UButton>
      </div>
    </template>
  </XModal>

  <!-- Delete Confirmation Modal -->
  <XModal
    modal-id="delete-staff"
    v-model="showDeleteModal"
    title="Delete Employee"
    size="md"
    @close="showDeleteModal = false"
  >
    <div class="p-4">
      <p class="text-gray-600 dark:text-gray-300">
        Are you sure you want to delete {{ selectedUserForDelete.firstName }} {{ selectedUserForDelete.lastName }}? 
        This action cannot be undone.
      </p>
    </div>

    <template #footer>
      <div class="flex justify-end gap-3">
        <UButton
          color="gray"
          variant="soft"
          @click="showDeleteModal = false"
        >
          Cancel
        </UButton>
        <UButton
          color="red"
          :loading="loading"
          @click="confirmDelete"
        >
          Delete Employee
        </UButton>
      </div>
    </template>
  </XModal>
</template>

// app/(app)/dashboardEmployer/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAction, useConvexAuth, useQuery, useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { XSummary } from "@/components/XSummary";
import { XTable } from "@/components/XTable";
import { XModal } from "@/components/XModal";
import { XDropdown } from "@/components/XDropdown";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { FormField } from "@/components/ui/FormField";
import { toast } from "@/lib/toast";

const columns = [
  { key: "firstName", label: "First Name", id: "firstName" },
  { key: "lastName", label: "Last Name", id: "lastName" },
  { key: "role", label: "Staff Role", id: "role" },
  { key: "email", label: "Email", id: "email" },
  { key: "lastEntryTime", label: "Last login time", id: "lastEntryTime" },
  { key: "actions", label: "Actions", id: "actions" },
];

export default function DashboardEmployerPage() {
  const router = useRouter();
  const { isAuthenticated } = useConvexAuth();

  const me = useQuery(api.users.getCurrentUser, isAuthenticated ? {} : "skip");

  // Redirect non-admins away as soon as the user record loads
  useEffect(() => {
    if (me === undefined) return; // still loading
    if (me === null || me.role !== "admin") {
      router.replace(me ? `/dashboardStaff/${me._id}` : "/login");
    }
  }, [me, router]);

  const employerId = me?._id as Id<"users"> | undefined;

  const staffList = useQuery(
    api.staff.listStaffByEmployer,
    employerId ? { employerId } : "skip"
  );
  const departments = useQuery(
    api.departments.listByEmployer,
    employerId ? { employerId } : "skip"
  );

  const today = new Date().toISOString().slice(0, 10);

  const dailySummary = useQuery(
    api.attendance.getEmployerDailySummary,
    employerId ? { employerId, date: today } : "skip"
  );

  const createStaffMutation = useMutation(api.staff.createStaffFromDashboard);
  const deleteStaffMutation = useMutation(api.staff.removeStaffByUserId);
  const inviteByEmail = useAction(api.invites.inviteStaffByEmail);
  const invitePending = useAction(api.invites.invitePendingStaff);

  const [loading, setLoading] = useState(false);
  const [showAddModal, setShowAddModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showInviteModal, setShowInviteModal] = useState(false);
  const [selectedForDelete, setSelectedForDelete] = useState<{ _id: string; firstName: string; lastName: string } | null>(null);

  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", role: "", department: "" });
  const [inviteEmail, setInviteEmail] = useState("");

  const staffData = (staffList ?? []).map((x: any) => {
    const date = x.lastEntryTime ? new Date(x.lastEntryTime) : null;
    return {
      ...x,
      _id: x.userId,
      lastEntryTime: date
        ? date.toLocaleString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "numeric", minute: "numeric", hour12: true })
        : "N/A",
    };
  });

  const departmentItems = (departments ?? []).map((d: any) => ({ name: d.name, id: d._id }));

  const itemsGenerator = (row: Record<string, unknown>) => [
    [{ label: "View Employee", icon: "i-heroicons-eye-20-solid", click: () => router.push(`/dashboardStaff/${row._id}`) }],
    [{ label: "Delete Employee", icon: "i-heroicons-trash-20-solid", click: () => { setSelectedForDelete(row as any); setShowDeleteModal(true); } }],
  ];

  const handleCreate = async () => {
    if (!employerId) return;
    setLoading(true);
    try {
      await createStaffMutation({
        employerId,
        firstName: form.firstName,
        lastName: form.lastName,
        email: form.email,
        role: form.role,
        departmentId: (form.department || undefined) as Id<"departments"> | undefined,
      });
      toast("Employee Successfully Created!", "success");
      setShowAddModal(false);
      setForm({ firstName: "", lastName: "", email: "", role: "", department: "" });
    } catch {
      toast("Failed to create employee", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async () => {
    if (!selectedForDelete) return;
    setLoading(true);
    try {
      await deleteStaffMutation({ userId: selectedForDelete._id as Id<"users"> });
      toast("Employee successfully deleted", "success");
    } catch {
      toast("Error deleting employee", "error");
    } finally {
      setLoading(false);
      setShowDeleteModal(false);
      setSelectedForDelete(null);
    }
  };

  const pendingInviteCount = (staffList ?? []).filter((s) => s.needsInvite).length;

  const handleInviteOne = async () => {
    if (!inviteEmail.trim()) {
      toast("Enter an email address", "error");
      return;
    }
    setLoading(true);
    try {
      const result = await inviteByEmail({ email: inviteEmail.trim() });
      if (result.success) {
        toast(`Invitation sent to ${result.email}`, "success");
        setInviteEmail("");
      } else {
        toast(result.message, "error");
      }
    } catch (e) {
      toast(e instanceof Error ? e.message : "Failed to send invite", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleInviteAll = async () => {
    setLoading(true);
    try {
      const result = await invitePending({});
      if (result.invited > 0) {
        toast(`Sent ${result.invited} invitation${result.invited !== 1 ? "s" : ""}`, "success");
      }
      if (result.failed > 0) {
        toast(`${result.failed} invite${result.failed !== 1 ? "s" : ""} failed`, "error");
      }
      if (result.invited === 0 && result.failed === 0) {
        toast("No pending staff to invite", "error");
      }
    } catch (e) {
      toast(e instanceof Error ? e.message : "Failed to send invites", "error");
    } finally {
      setLoading(false);
    }
  };

  const paginationData = { page: 1, count: 1, total: staffData.length };

  return (
    <main className="min-h-full bg-white p-4 md:p-10">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between">
        <div className="flex flex-col mb-4 md:mb-0">
          <span className="text-xl md:text-2xl font-bold">Welcome Admin</span>
          <span className="text-sm font-light">See Today&apos;s attendance overview..</span>
        </div>
        <div className="flex space-x-2">
          <button
            type="button"
            onClick={() => setShowInviteModal(true)}
            className="border-[#762CC0] cursor-pointer border py-3 px-5 space-x-2 rounded-md flex justify-center items-center gap-2 hover:bg-purple-50 transition-colors"
          >
            <svg width="20" height="20" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M9.922 3.29004C14.6963 1.66245 17.0834 0.848663 18.3674 2.13261C19.6513 3.41656 18.8375 5.80371 17.21 10.578L16.1016 13.8292C14.8517 17.4958 14.2267 19.3291 13.1964 19.4808C12.9195 19.5216 12.6328 19.4971 12.3587 19.4091C11.3395 19.0819 10.8007 17.1489 9.7231 13.283C9.4841 12.4255 9.3646 11.9967 9.0924 11.6692C9.0134 11.5742 8.9258 11.4866 8.8308 11.4076C8.5033 11.1354 8.0745 11.0159 7.21705 10.7769C3.35111 9.6993 1.41814 9.1605 1.0909 8.14127C1.00292 7.86724 0.97837 7.58053 1.01916 7.30355C1.17088 6.27332 3.00419 5.64834 6.6708 4.39838L9.922 3.29004Z" stroke="#1A1A1A" strokeWidth="2"/>
            </svg>
            <span>Send Invite{pendingInviteCount > 0 ? ` (${pendingInviteCount})` : ""}</span>
          </button>
          <button
            onClick={() => setShowAddModal(true)}
            className="bg-[#762CC0] text-white border py-3 px-5 space-x-2 rounded-md flex justify-center items-center gap-2"
          >
            <svg width="20" height="20" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M13 22.5H6.59087C5.04549 22.5 3.81631 21.748 2.71266 20.6966C0.453366 18.5441 4.1628 16.824 5.57757 15.9816C7.97679 14.553 10.8425 14.1575 13.5 14.7952" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M16.5 7C16.5 9.48528 14.4853 11.5 12 11.5C9.51472 11.5 7.5 9.48528 7.5 7C7.5 4.51472 9.51472 2.5 12 2.5C14.4853 2.5 16.5 4.51472 16.5 7Z" stroke="white" strokeWidth="2"/>
              <path d="M19 23.7426V19.5M19 19.5V15.2574M19 19.5H14.7574M19 19.5H23.2427" stroke="white" strokeWidth="2" strokeLinecap="round"/>
            </svg>
            <span>Add employee</span>
          </button>
        </div>
      </div>

      <div className="mt-8 md:mt-20">
        <XSummary
          totalEmployees={staffData.length}
          presentToday={dailySummary?.uniqueStaffSignedIn ?? 0}
          lateToday={dailySummary?.late ?? 0}
          absentToday={Math.max(0, staffData.length - (dailySummary?.uniqueStaffSignedIn ?? 0))}
        />
        <XTable columns={columns} tableData={staffData} paginationData={paginationData} itemsGenerator={itemsGenerator} />
      </div>

      {/* Add Employee Modal */}
      <XModal
        open={showAddModal}
        onClose={() => { setShowAddModal(false); setForm({ firstName: "", lastName: "", email: "", role: "", department: "" }); }}
        title="Create Employee"
        size="2xl"
        footer={
          <div className="flex justify-end gap-3">
            <Button color="gray" variant="soft" onClick={() => setShowAddModal(false)}>Cancel</Button>
            <Button loading={loading} onClick={handleCreate}>Create Employee</Button>
          </div>
        }
      >
        <div className="space-y-5 w-full">
          <FormField label="First Name" name="firstName">
            <Input placeholder="First Name" size="lg" value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} />
          </FormField>
          <FormField label="Last Name" name="lastName">
            <Input placeholder="Last Name" size="lg" value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} />
          </FormField>
          <FormField label="Email" name="email">
            <Input type="email" placeholder="Email Address" size="lg" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />
          </FormField>
          <FormField label="Role" name="role">
            <Input placeholder="Role" size="lg" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} />
          </FormField>
          <FormField label="Department" name="department">
            <XDropdown items={departmentItems} onSelect={(val) => setForm({ ...form, department: String(val.id ?? "") })} />
          </FormField>
        </div>
      </XModal>

      {/* Invite Modal */}
      <XModal
        open={showInviteModal}
        onClose={() => { setShowInviteModal(false); setInviteEmail(""); }}
        title="Send Staff Invites"
        size="lg"
        footer={
          <div className="flex justify-end gap-3">
            <Button color="gray" variant="soft" onClick={() => setShowInviteModal(false)}>Close</Button>
          </div>
        }
      >
        <div className="space-y-6">
          <p className="text-gray-600 text-sm">
            Invite staff to create their Clerk account. They will receive an email to set their password.
          </p>
          <FormField label="Email" name="inviteEmail">
            <Input
              type="email"
              placeholder="staff@company.com"
              size="lg"
              value={inviteEmail}
              onChange={(e) => setInviteEmail(e.target.value)}
            />
          </FormField>
          <Button loading={loading} onClick={handleInviteOne} className="w-full">
            Send Invitation
          </Button>
          {pendingInviteCount > 0 && (
            <div className="border-t pt-6">
              <p className="text-sm text-gray-600 mb-3">
                {pendingInviteCount} staff member{pendingInviteCount !== 1 ? "s" : ""} haven&apos;t been invited yet.
              </p>
              <Button loading={loading} variant="outline" onClick={handleInviteAll} className="w-full">
                Invite All Pending Staff
              </Button>
            </div>
          )}
        </div>
      </XModal>

      {/* Delete Confirmation Modal */}
      <XModal
        open={showDeleteModal}
        onClose={() => setShowDeleteModal(false)}
        title="Delete Employee"
        size="md"
        footer={
          <div className="flex justify-end gap-3">
            <Button color="gray" variant="soft" onClick={() => setShowDeleteModal(false)}>Cancel</Button>
            <Button color="red" loading={loading} onClick={handleDelete}>Delete Employee</Button>
          </div>
        }
      >
        <div className="p-4">
          <p className="text-gray-600">
            Are you sure you want to delete{" "}
            <strong>{selectedForDelete?.firstName} {selectedForDelete?.lastName}</strong>? This action cannot be undone.
          </p>
        </div>
      </XModal>
    </main>
  );
}
