// app/(app)/dashboardStaff/[id]/page.tsx
"use client";

import { use, useEffect, useState } from "react";
import { useConvexAuth, useMutation, useQuery } from "convex/react";
import { Line } from "react-chartjs-2";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { saveAs } from "file-saver";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { FormField } from "@/components/ui/FormField";
import { XTable } from "@/components/XTable";
import { toast } from "@/lib/toast";

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);

const columns = [
  { key: "entryDate", label: "Date", id: "entryDate" },
  { key: "entryTime", label: "Sign in Time", id: "entryTime" },
  { key: "status", label: "Status", id: "status" },
];

const paginationData = { page: 1, count: 1, total: 0 };

const chartOptions = {
  responsive: true,
  scales: {
    y: { beginAtZero: true, ticks: { stepSize: 1 }, title: { display: true, text: "Number of Days", font: { size: 14 } } },
    x: { title: { display: true, text: "Months", font: { size: 14 } } },
  },
  plugins: {
    legend: { display: true, position: "top" as const },
    title: { display: true, text: "Staff Attendance Trends", font: { size: 16, weight: "bold" as const }, padding: 20 },
    tooltip: {
      callbacks: {
        label: (ctx: any) => `${ctx.dataset.label}: ${ctx.parsed.y} day${ctx.parsed.y !== 1 ? "s" : ""}`,
      },
    },
  },
  elements: { line: { tension: 0.4 }, point: { radius: 5, hoverRadius: 7 } },
  interaction: { intersect: false, mode: "index" as const },
};

interface LogEntry {
  entryDate: Date;
  entryTime: Date;
  late?: boolean;
  status?: string;
  _originalEntryDate?: Date;
  _originalEntryTime?: Date;
  [key: string]: unknown;
}

function todayString() {
  return new Date().toISOString().slice(0, 10);
}

export default function StaffDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { isAuthenticated } = useConvexAuth();
  const me = useQuery(api.users.getCurrentUser, isAuthenticated ? {} : "skip");
  const isAdmin = me?.role === "admin";
  const isOwnDashboard = me?._id === id;

  const staffData = useQuery(api.staff.getStaffDetail, { staffUserId: id as Id<"users"> });
  const todayEntry = useQuery(
    api.attendance.getTodayEntry,
    isOwnDashboard ? { staffUserId: id as Id<"users">, today: todayString() } : "skip"
  );
  const clockIn = useMutation(api.attendance.clockIn);

  const [allLogs, setAllLogs] = useState<LogEntry[]>([]);
  const [filtered, setFiltered] = useState<LogEntry[]>([]);
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [chartData, setChartData] = useState<{ labels: string[]; datasets: any[] }>({ labels: [], datasets: [] });
  const [signingIn, setSigningIn] = useState(false);

  useEffect(() => {
    const today = new Date();
    const ago30 = new Date();
    ago30.setDate(today.getDate() - 30);
    setEndDate(today.toISOString().split("T")[0]!);
    setStartDate(ago30.toISOString().split("T")[0]!);
  }, []);

  useEffect(() => {
    if (!staffData) return;
    const formatted: LogEntry[] = staffData.entryLogs.map((val: any) => {
      const entryDate = new Date(val.entryDate);
      const entryTime = new Date(val.entryTime);
      return {
        ...val,
        _originalEntryDate: entryDate,
        _originalEntryTime: entryTime,
        entryDate: entryDate.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }),
        entryTime: entryTime.toLocaleTimeString("en-US", { hour: "numeric", minute: "numeric", hour12: true }),
        status: val.late ? "Late" : "On Time",
      };
    });
    setAllLogs(formatted);
  }, [staffData]);

  useEffect(() => {
    if (!startDate || !endDate) { setFiltered(allLogs); return; }
    const s = new Date(startDate); s.setHours(0, 0, 0, 0);
    const e = new Date(endDate); e.setHours(23, 59, 59, 999);
    const f = allLogs.filter((l) => { const d = l._originalEntryDate!; return d >= s && d <= e; });
    setFiltered(f);
  }, [startDate, endDate, allLogs]);

  useEffect(() => {
    const stats = filtered.reduce<Record<string, { early: number; late: number }>>((acc, log) => {
      const d = log._originalEntryDate!;
      const key = d.toLocaleString("en-US", { month: "long", year: "numeric" });
      if (!acc[key]) acc[key] = { early: 0, late: 0 };
      if (log.late) acc[key]!.late += 1;
      else acc[key]!.early += 1;
      return acc;
    }, {});
    setChartData({
      labels: Object.keys(stats),
      datasets: [
        { label: "Early Arrivals (Before 9 AM)", backgroundColor: "#4CAF50", borderColor: "#4CAF50", data: Object.values(stats).map((s) => s.early), fill: false },
        { label: "Late Arrivals (After 9 AM)", backgroundColor: "#FF5252", borderColor: "#FF5252", data: Object.values(stats).map((s) => s.late), fill: false },
      ],
    });
  }, [filtered]);

  const staffName = staffData ? `${staffData.staff.firstName || ""} ${staffData.staff.lastName || ""}`.trim() : "";

  const handleClockIn = async () => {
    setSigningIn(true);
    try {
      await clockIn({ today: todayString() });
      toast("Signed in successfully!", "success");
    } catch (e) {
      toast(e instanceof Error ? e.message : "Failed to sign in", "error");
    } finally {
      setSigningIn(false);
    }
  };

  const exportToCSV = () => {
    if (filtered.length === 0) { alert("No data to export."); return; }
    const headers = ["Date", "Sign in Time", "Status"];
    const rows = [...filtered]
      .sort((a, b) => b._originalEntryDate!.getTime() - a._originalEntryDate!.getTime())
      .map((row) => {
        const d = row._originalEntryDate!.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
        const t = row._originalEntryTime!.toLocaleTimeString("en-US", { hour: "numeric", minute: "numeric", hour12: true });
        return [d, t, row.late ? "Late" : "On Time"].map((f) => (String(f).includes(",") ? `"${f}"` : f)).join(",");
      });
    const csv = [headers.join(","), ...rows].join("\n");
    const filename = `${staffName.replace(/\s+/g, "_")}_attendance_${startDate || "all"}_to_${endDate || "all"}.csv`;
    saveAs(new Blob([csv], { type: "text/csv;charset=utf-8;" }), filename);
  };

  return (
    <div className="w-full p-2 sm:p-4">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
          <h1 className="text-2xl font-semibold">{staffName} Attendance Summary</h1>
          <div className="flex flex-wrap gap-3">
            {isOwnDashboard && (
              todayEntry === undefined ? null : todayEntry ? (
                <span className="inline-flex items-center px-4 py-2 rounded-lg bg-green-50 text-green-700 text-sm font-medium border border-green-200">
                  Signed in today at{" "}
                  {new Date(todayEntry.entryTime).toLocaleTimeString("en-US", {
                    hour: "numeric",
                    minute: "numeric",
                    hour12: true,
                  })}
                  {todayEntry.late ? " (Late)" : " (On Time)"}
                </span>
              ) : (
                <Button loading={signingIn} onClick={handleClockIn} color="primary" size="md">
                  Sign In Now
                </Button>
              )
            )}
          <Button onClick={exportToCSV} color="primary" size="md" className="flex items-center gap-2">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Export to CSV
          </Button>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-4 mb-6">
          <div className="flex flex-col sm:flex-row gap-4 items-end">
            <div className="flex-1">
              <FormField label="Start Date" name="startDate">
                <Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} size="md" />
              </FormField>
            </div>
            <div className="flex-1">
              <FormField label="End Date" name="endDate">
                <Input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} size="md" />
              </FormField>
            </div>
            <Button onClick={() => { setStartDate(""); setEndDate(""); }} color="gray" variant="outline" size="md">
              Clear
            </Button>
          </div>
          {filtered.length > 0 && (
            <p className="text-sm text-gray-600 mt-3">
              Showing {filtered.length} record{filtered.length !== 1 ? "s" : ""}
              {startDate && endDate && ` from ${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`}
            </p>
          )}
        </div>

        {isAdmin && chartData.labels.length > 0 && (
          <div className="bg-white rounded-lg shadow p-3 sm:p-6 mb-8">
            <div className="h-[300px] md:h-[400px] lg:h-[500px]">
              <Line data={chartData} options={chartOptions} />
            </div>
          </div>
        )}

        <XTable columns={columns} tableData={filtered as Record<string, unknown>[]} paginationData={paginationData} />
      </div>
    </div>
  );
}

// src/pages/dashboardStaff/[id]/index.vue
<script lang="ts" setup>
import { getStaff } from '@/composables/services/data/data';
import { useUserStore } from '@/store/userStore';
import { Line } from 'vue-chartjs'
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js'
import { saveAs } from 'file-saver';
import Button from '@/components/ui/Button.vue';
import Input from '@/components/ui/Input.vue';
import FormField from '@/components/ui/FormField.vue';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend)

const store = useUserStore();
const $route = useRoute();

definePageMeta({
  // layout: computed(() => userType.value === 'employer' ? 'default' : 'staff')
})

const allEntryLogs = ref<any[]>([]); // Store original unfiltered data
const staffTableData = ref<any[]>([]);

const paginationData = {
  page: 1,        
  count: 5,       
  total: 10,       
  prev: null,      
  next: 2      
};

const columns = [
  {
    key: "entryDate",
    label: "Date",
    id: "entryDate",
  },
  {
    key: "entryTime",
    label: "Sign in Time",
    id: "entryTime",
  },
  {
    key: "status",
    label: "Status",
    id: "status",
  },
];

const items = (row: any) => [
  [
    { "id": "18:00", "name": "" },
  ]
];

// Date filter state
const startDate = ref<string>('');
const endDate = ref<string>('');

// Set default date range (last 30 days)
const setDefaultDateRange = () => {
  const today = new Date();
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(today.getDate() - 30);
  
  endDate.value = today.toISOString().split('T')[0];
  startDate.value = thirtyDaysAgo.toISOString().split('T')[0];
};

// Filter data based on date range
const filterDataByDateRange = () => {
  if (!startDate.value || !endDate.value) {
    staffTableData.value = allEntryLogs.value;
    return;
  }

  const start = new Date(startDate.value);
  start.setHours(0, 0, 0, 0); // Start of day
  const end = new Date(endDate.value);
  end.setHours(23, 59, 59, 999); // End of day

  staffTableData.value = allEntryLogs.value.filter((log: any) => {
    const entryDate = log._originalEntryDate || new Date(log.entryDate);
    return entryDate >= start && entryDate <= end;
  });
  
  // Update chart with filtered data
  updateChart();
};

// Watch for date changes
watch([startDate, endDate], () => {
  filterDataByDateRange();
});

const chartData = ref<{
  labels: string[];
  datasets: {
    label: string;
    backgroundColor: string;
    borderColor: string;
    data: number[];
    fill: boolean;
  }[];
}>({
  labels: [],
  datasets: []
});

const chartOptions = {
  responsive: true,
  scales: {
    y: {
      beginAtZero: true,
      ticks: {
        stepSize: 1
      },
      title: {
        display: true,
        text: 'Number of Days',
        font: {
          size: 14
        }
      }
    },
    x: {
      title: {
        display: true,
        text: 'Months',
        font: {
          size: 14
        }
      }
    }
  },
  plugins: {
    legend: {
      display: true,
      position: 'top' as const,
      labels: {
        padding: 20,
        font: {
          size: 12
        }
      }
    },
    title: {
      display: true,
      text: 'Staff Attendance Trends',
      font: {
        size: 16,
        weight: 'bold' as const
      },
      padding: 20
    },
    tooltip: {
      callbacks: {
        label: (context: any) => {
          const label = context.dataset.label || '';
          const value = context.parsed.y;
          return `${label}: ${value} day${value !== 1 ? 's' : ''}`;
        },
        title: (tooltipItems: any[]) => {
          return tooltipItems[0].label;
        }
      }
    }
  },
  elements: {
    line: {
      tension: 0.4
    },
    point: {
      radius: 5,
      hoverRadius: 7
    }
  },
  interaction: {
    intersect: false,
    mode: 'index' as const
  }
};

const exportToCSV = () => {
  if (staffTableData.value.length === 0) {
    alert('No data to export. Please select a date range with data.');
    return;
  }

  // Create CSV headers
  const headers = ['Date', 'Sign in Time', 'Status'];
  
  // Convert filtered data to CSV format - sort by date descending
  const sortedData = [...staffTableData.value].sort((a, b) => {
    const dateA = a._originalEntryDate || new Date(a.entryDate);
    const dateB = b._originalEntryDate || new Date(b.entryDate);
    return dateB.getTime() - dateA.getTime(); // Newest first
  });
  
  const csvData = sortedData.map(row => {
    // Use original dates for CSV (formatted nicely)
    const dateStr = row._originalEntryDate 
      ? row._originalEntryDate.toLocaleDateString('en-US', { 
          month: 'long', 
          day: 'numeric', 
          year: 'numeric' 
        })
      : row.entryDate;
    const timeStr = row._originalEntryTime
      ? row._originalEntryTime.toLocaleTimeString('en-US', { 
          hour: 'numeric', 
          minute: 'numeric', 
          hour12: true 
        })
      : row.entryTime;
    
    return [
      dateStr || '',
      timeStr || '',
      row.late ? 'Late' : 'On Time'
    ].map(field => {
      // Escape commas and quotes in CSV
      const stringField = String(field);
      if (stringField.includes(',') || stringField.includes('"') || stringField.includes('\n')) {
        return `"${stringField.replace(/"/g, '""')}"`;
      }
      return stringField;
    }).join(',');
  });
  
  // Combine headers and data
  const csvContent = [headers.join(','), ...csvData].join('\n');
  
  // Create filename with date range and staff name
  const startStr = startDate.value || 'all';
  const endStr = endDate.value || 'all';
  const staffName = staff.value.replace(/\s+/g, '_');
  const filename = `${staffName}_attendance_${startStr}_to_${endStr}.csv`;
  
  // Create and download the file
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, filename);
};

const clearFilters = () => {
  startDate.value = '';
  endDate.value = '';
  filterDataByDateRange();
};

const updateChart = () => {
  // Process data for chart (using filtered data)
  const monthlyStats = staffTableData.value.reduce((acc: any, log: any) => {
    const date = log._originalEntryDate || new Date(log.entryDate);
    const monthYear = date.toLocaleString('en-US', { month: 'long', year: 'numeric' });
    
    if (!acc[monthYear]) {
      acc[monthYear] = { early: 0, late: 0 };
    }
    
    if (!log.late) {
      acc[monthYear].early += 1;
    } else {
      acc[monthYear].late += 1;
    }
    
    return acc;
  }, {});

  chartData.value = {
    labels: Object.keys(monthlyStats),
    datasets: [
      {
        label: 'Early Arrivals (Before 9 AM)',
        backgroundColor: '#4CAF50',
        borderColor: '#4CAF50',
        data: (Object.values(monthlyStats) as { early: number; late: number }[]).map(stat => stat.early),
        fill: false
      },
      {
        label: 'Late Arrivals (After 9 AM)',
        backgroundColor: '#FF5252',
        borderColor: '#FF5252',
        data: (Object.values(monthlyStats) as { early: number; late: number }[]).map(stat => stat.late),
        fill: false
      }
    ]
  };
};

const staff = ref('')
onMounted(async () => {
  setDefaultDateRange();
  
  const staffData = await getStaff($route.params.id);
  staff.value = staffData.staff.firstName + ' ' + staffData.staff.lastName;
  
  // Store original data with formatted dates for display
  const formattedLogs = staffData.entryLogs.map((val: any) => {
    const originalEntryDate = new Date(val.entryDate);
    const originalEntryTime = new Date(val.entryTime);
    
    return {
      ...val,
      entryDate: originalEntryDate.toLocaleDateString('en-US', { 
        month: 'long', 
        day: 'numeric', 
        year: 'numeric' 
      }),
      entryTime: originalEntryTime.toLocaleTimeString('en-US', { 
        hour: 'numeric', 
        minute: 'numeric', 
        hour12: true 
      }),
      // Keep original dates for filtering
      _originalEntryDate: originalEntryDate,
      _originalEntryTime: originalEntryTime,
      status: val.late ? 'Late' : 'On Time'
    };
  });
  
  allEntryLogs.value = formattedLogs;
  filterDataByDateRange();
});
</script>

<template>
  <main class="w-full p-2 sm:p-4"> 
    <div class="max-w-7xl mx-auto">
      <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6"> 
        <h1 class="text-2xl font-semibold">{{ staff }} Attendance Summary</h1>
        <Button 
          @click="exportToCSV"
          color="primary"
          size="md"
          class="flex items-center gap-2"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Export to CSV
        </Button>
      </div>

      <!-- Date Range Filter -->
      <div class="bg-white rounded-lg shadow p-4 mb-6">
        <div class="flex flex-col sm:flex-row gap-4 items-end">
          <div class="flex-1">
            <FormField label="Start Date" name="startDate">
              <Input
                v-model="startDate"
                type="date"
                size="md"
              />
            </FormField>
          </div>
          <div class="flex-1">
            <FormField label="End Date" name="endDate">
              <Input
                v-model="endDate"
                type="date"
                size="md"
              />
            </FormField>
          </div>
          <div class="flex gap-2">
            <Button
              @click="clearFilters"
              color="gray"
              variant="outline"
              size="md"
            >
              Clear
            </Button>
          </div>
        </div>
        <p v-if="staffTableData.length > 0" class="text-sm text-gray-600 mt-3">
          Showing {{ staffTableData.length }} record{{ staffTableData.length !== 1 ? 's' : '' }} 
          <span v-if="startDate && endDate">
            from {{ new Date(startDate).toLocaleDateString() }} to {{ new Date(endDate).toLocaleDateString() }}
          </span>
        </p>
      </div>

      <div v-if="store.$state.userRole === 'Admin'" class="bg-white rounded-lg shadow p-3 sm:p-6 mb-8">
        <div class="h-[300px] md:h-[400px] lg:h-[500px]">
          <Line :data="chartData" :options="chartOptions" />
        </div>
      </div>
      
      <XTable 
        :columns="columns" 
        :pagination-data="paginationData" 
        :table-data="staffTableData"
      />
    </div>
  </main>
</template>
